### ISSUE TITLE
how can make user.getFullUser?

### ISSUE THREAD

**Issue by EiPP4ssenger** [sochix/TLSharp#148]
hello

I'm trying to use TLSharp to get full user info from and user_id but this lib don't implement this method !

API ref ([https://core.telegram.org/method/users.getFullUser](https://core.telegram.org/method/users.getFullUser))

Is there any other method to get fulluser ?

(excuse me if my EN is not very well )

**Comment by chusothe41** [comment]
I'm working on it. When it's ready I will try to commit it

**Comment by eippassenger** [comment]
@chusothe41  Thanks, i'm trying to add this method based on this [JAVA sample ](https://github.com/rubenlagus/Deepthought/blob/master/src/main/java/org/telegram/api/functions/users/TLRequestUsersGetFullUser.java) but unfortunately can't.
Because i haven't good knowledge about MTProto ....

Thanks again.

**Comment by chusothe41** [comment]
@eippassenger https://github.com/sochix/TLSharp/pull/154
