### ISSUE TITLE
Constructor Code Is Incomplete

### ISSUE THREAD

**Issue by EbiPenMan** [sochix/TLSharp#193]
Hi 
I try to GetContacts but take a error: invalid constructor code

I debug and get this code: E26F42F1
I founded if in https://core.telegram.org/schema
`userStatusRecently#e26f42f1 = UserStatus;`

And add it:
`{0xe26f42f1, typeof (UserStatusOfflineConstructor)},`

But I get error again with this code: 5A1309B
I search it on  https://core.telegram.org/schema but not found it.

**Comment by Di-Roll** [comment]
Show your code.
This
```
var contacts = await _client.GetContacts();
foreach (var contact1 in contacts)
{
     var contact = (ContactConstructor) contact1;
}
```
works fine for me.

**Comment by XyLoNaMiyX** [comment]
https://core.telegram.org/schema is highly outdated. The problem is the same as [this](https://github.com/sochix/TLSharp/issues/201#issuecomment-246174219).

**Comment by amastaneh** [comment]
Hi, 
We have problem with parse `UserStatus` in `GetContactsRequest.OnResponse` and i think in all

In `UserContactConstructor.Read` method (and all other methods), we have exception on `this.status = TL.Parse<UserStatus>(reader);` because based on https://core.telegram.org/type/UserStatus we have two conditions

**With Constructors**
userStatusEmpty#9d05049 = UserStatus;
userStatusOnline#edb93949 expires:int = UserStatus;
userStatusOffline#8c703f was_online:int = UserStatus;

**Without Constructors**
userStatusRecently#e26f42f1 = UserStatus;
userStatusLastWeek#7bf09fc = UserStatus;
userStatusLastMonth#77ebc742 = UserStatus;

When we call `TL.Parse` for all of them based on `userStatusRecently` and `userStatusLastWeek` and `userStatusLastMonth` we get exception because they haven't constructors and those are just value.

I think there's a solution for solve this problem
We can build three Constructor for  `userStatusRecently` and `userStatusLastWeek` and `userStatusLastMonth` with empty read method.

**Comment by sochix** [comment]
library updated
