### ISSUE TITLE
TLRequestCreateChat - INPUT_CONSTRUCTOR_INVALID

### ISSUE THREAD

**Issue by rafalrozek** [sochix/TLSharp#253]
Hey again, please, don't close this thread again beacuse I don't know why it doesn't work:
http://pastebin.com/raw/WJKUJEiS
Can anyone build a Request to create a new Chat and add my account to this chat? Please :(

**Comment by sochix** [comment]
I bet it's problem with TlVector. Use generic version, e.g
TlVector<someType>

18 окт. 2016 г. 23:18 пользователь "rafalrozek" <notifications@github.com>
написал:

Hey again, please, don't close this thread again beacuse I don't know why
it doesn't work:
var c = new TLRequestCreateChat()
{
users = new TLVector(),
title = "dddd",

        };
        await client.SendRequestAsync<TLMessage>(c);

Can anyone create a Request to create a new Chat and add my account to this
chat? Please :(

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sochix/TLSharp/issues/253>, or mute the thread

**Comment by rafalrozek** [comment]
Yes, I used a generic version like that:
users = new TLVector<TLAbsInputUser>(),
but i dont add a new user, thats the problem. How to add a new user to TLVector?

**Comment by sochix** [comment]
I removed non-generic TlVector, and fix bug in generic TlVector<> serialization. So, try now
