### ISSUE TITLE
TLUserStatusOffline was_online value

### ISSUE THREAD

**Issue by Makcumyc1981** [sochix/TLSharp#365]
Hi friends! 
i have a problem. when i search a user in my  contact list, i get his status like TLUserStatusOffline.
Can you help me, how to get the status.was_online  value from user (its Unix Date value). Thanks!
My code:
//find recipient in contacts
            var user = result.users.lists
                .Where(x => x.GetType() == typeof(TLUser))
                .Cast<TLUser>()
                .FirstOrDefault(x => x.phone == TelNum);

if(user.status.Constructor==9203775)  //user Offline
                {
                   .... //get was_online value from user.status

                }

**Comment by hadi77ir** [comment]
Just use type casting like this:
`((TLUserStatusOffline)user.status).was_online` and it gives you an Int32 containing the value in Unix time format.

You can also use reflection and casting instead of checking Constructor field. It would look like this:
`if(user.status.GetType() == typeof(TLUserStatusOffline)`

**Comment by Makcumyc1981** [comment]
Hi! Thank you!  It working!

**Comment by hadi77ir** [comment]
I'm glad to be useful to the community.
@Makcumyc1981 If your problem is solved, close the issue.

Thanks.
