### ISSUE TITLE
Overriding default telegram server IP

### ISSUE THREAD

**Issue by ridicoulous** [sochix/TLSharp#441]
I think [this ](https://github.com/sochix/TLSharp/issues/439#issuecomment-291819756) comment is correct about reason of deactivating accounts. How I can override default IP-address of telegram server and use addresses for development and production from my  telegram configs?

**Comment by hadi77ir** [comment]
As I said in that comment, it is about session storage and TelegramClient. Default IP Address is stored in Session.cs and every time it connects to this server, it may get a DC change (switch to another IP address) so that IP will be saved inside the session file. After exiting the app, and opening again, the session will be reloaded.
All we have to do is to add two parameters (IP and Port) to constructor of TelegramClient and give them to FileSessionStore. You can do it yourself, it's very easy.

**Comment by mostafa8026** [comment]
Hi hadi. Could you give us an example?
