### ISSUE TITLE
Delete Contact TLSharp

### ISSUE THREAD

**Issue by MoienTajik** [sochix/TLSharp#509]
Hi ,
How can i implement delete contact using TLSharp ? 
I tried this :

```
TLRequestDeleteContact req = new TLRequestDeleteContact
            {
                id = new TLInputUser
                {
                    user_id = //USER ID
                }
            };

            TLRequestDeleteContact updates = await _client.SendRequestAsync<TLRequestDeleteContact>(req);
```

but i got :

> CONTACT_ID_INVALID

Thanks .

**Comment by jorgelg** [comment]
I guess you're filling user_id with a valid user_id recovered from user's contacts list using context.GetContactsAsync()?

**Comment by MoienTajik** [comment]
@jorgelg I got that USER_ID from TLImportContactAsync() response and i believe that User ID is correct and problem is from another section, maybe from TLRequestDeleteContact .

**Comment by jorgelg** [comment]
As far as I knew TLImportContactsAsync is to add contacts to your contacts list and in order to retrieve your contacts list "GetContactsAsync" is needed, anyways, have you tried debugging step by step? You probably should inspect what's happening inside TLRequestDeleteContact as well

**Comment by MoienTajik** [comment]
Yeah , I perform line by line debugging and i think TLRequestDeleteContact is not implemented correctly .

**Comment by hadi77ir** [comment]
`TLRequestDeleteContact` implementation only contains serializing and deserializing based on the definition from TL Scheme, so the problem is not from TLSharp.
You are not providing `access_hash` data in `TLInputUser` properties. You need to fill it with `access_hash` you have for accessing this user (`TLImportContactAsync` should have given you this information, also if you have a `TLUser` object you can get the `access_hash` from it).
